In [4]:
# data reading, writing, exploration, cleaning
import pandas as pd
# array creation and operation
import numpy as np 
# plotting library
import matplotlib.pyplot as plt 
# data visualization library
import seaborn as sns
# remove warnings
import warnings
warnings.filterwarnings('ignore')

In [5]:
# loading the dataset
df = pd.read_csv("C:/Users/Dell/OneDrive/Desktop/Data Engineer Project/Project-1/order_dataset.csv")
df

,order_id,user_name,order_status,order_date,order_approved_date,pickup_date,delivered_date,estimated_time_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,delivered,7/24/2018 20:41,7/26/2018 3:24,7/26/2018 14:31,8/7/2018 15:27,8/13/2018 0:00
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,delivered,8/8/2018 8:38,8/8/2018 8:55,8/8/2018 13:50,8/17/2018 18:06,9/4/2018 0:00
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,delivered,11/18/2017 19:28,11/18/2017 19:45,11/22/2017 13:39,12/2/2017 0:28,12/15/2017 0:00
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,delivered,2/13/2018 21:18,2/13/2018 22:20,2/14/2018 19:46,2/16/2018 18:17,2/26/2018 0:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,6359f309b166b0196dbf7ad2ac62bb5a,delivered,3/9/2017 9:54,3/9/2017 9:54,3/10/2017 11:18,3/17/2017 15:08,3/28/2017 0:00
99437,63943bddc261676b46f01ca7ac2f7bd8,da62f9e57a76d978d02ab5362c509660,delivered,2/6/2018 12:58,2/6/2018 13:10,2/7/2018 23:22,2/28/2018 17:37,3/2/2018 0:00
99438,83c1379a015df1e13d02aae0204711ab,737520a9aad80b3fbbdad19b66b37b30,delivered,8/27/2017 14:46,8/27/2017 15:04,8/28/2017 20:52,9/21/2017 11:24,9/27/2017 0:00
99439,11c177c8e97725db2631073c19f07b62,5097a5312c8b157bb7be58ae360ef43c,delivered,1/8/2018 21:28,1/8/2018 21:36,1/12/2018 15:35,1/25/2018 23:32,2/15/2018 0:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,60350aa974b26ff12caad89e55993bd6,delivered,3/8/2018 20:57,3/9/2018 11:20,3/9/2018 22:11,3/16/2018 13:08,4/3/2018 0:00

In [6]:
# checking null values 
df.isnull().sum()

order_id                      0
user_name                     0
order_status                  0
order_date                    0
order_approved_date         160
pickup_date                1783
delivered_date             2965
estimated_time_delivery       0
dtype: int64

* filling missing values :

In [7]:
# Fill missing values
df['order_approved_date'] = df['order_approved_date'].fillna(df['order_date'])

df['pickup_date'] = df['pickup_date'].fillna(df['order_approved_date'])

df['delivered_date'] = df['delivered_date'].fillna(df['pickup_date'])

In [8]:
df.isnull().sum()

order_id                   0
user_name                  0
order_status               0
order_date                 0
order_approved_date        0
pickup_date                0
delivered_date             0
estimated_time_delivery    0
dtype: int64

In [9]:
df

,order_id,user_name,order_status,order_date,order_approved_date,pickup_date,delivered_date,estimated_time_delivery
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,10/2/2017 10:56,10/2/2017 11:07,10/4/2017 19:55,10/10/2017 21:25,10/18/2017 0:00
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,delivered,7/24/2018 20:41,7/26/2018 3:24,7/26/2018 14:31,8/7/2018 15:27,8/13/2018 0:00
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,delivered,8/8/2018 8:38,8/8/2018 8:55,8/8/2018 13:50,8/17/2018 18:06,9/4/2018 0:00
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,delivered,11/18/2017 19:28,11/18/2017 19:45,11/22/2017 13:39,12/2/2017 0:28,12/15/2017 0:00
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,delivered,2/13/2018 21:18,2/13/2018 22:20,2/14/2018 19:46,2/16/2018 18:17,2/26/2018 0:00
...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,6359f309b166b0196dbf7ad2ac62bb5a,delivered,3/9/2017 9:54,3/9/2017 9:54,3/10/2017 11:18,3/17/2017 15:08,3/28/2017 0:00
99437,63943bddc261676b46f01ca7ac2f7bd8,da62f9e57a76d978d02ab5362c509660,delivered,2/6/2018 12:58,2/6/2018 13:10,2/7/2018 23:22,2/28/2018 17:37,3/2/2018 0:00
99438,83c1379a015df1e13d02aae0204711ab,737520a9aad80b3fbbdad19b66b37b30,delivered,8/27/2017 14:46,8/27/2017 15:04,8/28/2017 20:52,9/21/2017 11:24,9/27/2017 0:00
99439,11c177c8e97725db2631073c19f07b62,5097a5312c8b157bb7be58ae360ef43c,delivered,1/8/2018 21:28,1/8/2018 21:36,1/12/2018 15:35,1/25/2018 23:32,2/15/2018 0:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,60350aa974b26ff12caad89e55993bd6,delivered,3/8/2018 20:57,3/9/2018 11:20,3/9/2018 22:11,3/16/2018 13:08,4/3/2018 0:00

In [10]:
def transform_datetime_column(df, column_name, prefix):
    # Convert the column to datetime
    df[column_name] = pd.to_datetime(df[column_name])
    
    # Split Date and Time
    df[f'{prefix}_Date'] = df[column_name].dt.date
    df[f'{prefix}_Time'] = df[column_name].dt.time
    
    # Extract Year, Month, Day, and Season
    df[f'{prefix}_Year'] = df[column_name].dt.year
    df[f'{prefix}_Month'] = df[column_name].dt.month
    df[f'{prefix}_Day'] = df[column_name].dt.day
    
    # Function to determine the season
    def get_season(month):
        if month in [12, 1, 2]:
            return 'Winter'
        elif month in [3, 4, 5]:
            return 'Spring'
        elif month in [6, 7, 8]:
            return 'Summer'
        else:
            return 'Fall'
    
    df[f'{prefix}_Season'] = df[f'{prefix}_Month'].apply(get_season)
    
    # Extract Hour, Minute, Second, AM/PM, and Time of Day
    df[f'{prefix}_Hour'] = df[column_name].dt.hour
    df[f'{prefix}_Minute'] = df[column_name].dt.minute
    df[f'{prefix}_AM/PM'] = df[column_name].dt.strftime('%p')
    
    # Function to determine the time of day
    def get_period(hour):
        if 5 <= hour < 12:
            return 'Morning'
        elif 12 <= hour < 17:
            return 'Afternoon'
        elif 17 <= hour < 21:
            return 'Evening'
        else:
            return 'Night'
    
    df[f'{prefix}_TimeOfDay'] = df[f'{prefix}_Hour'].apply(get_period)
    
    return df

In [11]:
df = transform_datetime_column(df, 'order_date', 'order')
df = transform_datetime_column(df, 'order_approved_date', 'order_approved')
df = transform_datetime_column(df, 'pickup_date', 'pickup')
df = transform_datetime_column(df, 'delivered_date', 'delivered')

In [13]:
# Function to extract Year, Month, Day, and Season
def extract_date_components(df, column_name, prefix):
    # Convert the column to datetime
    df[column_name] = pd.to_datetime(df[column_name])
    
    # Extract Year, Month, and Day
    df[f'{prefix}_Year'] = df[column_name].dt.year
    df[f'{prefix}_Month'] = df[column_name].dt.month
    df[f'{prefix}_Day'] = df[column_name].dt.day
    
    # Function to determine the season
    def get_season(month):
        if month in [12, 1, 2]:
            return 'Winter'
        elif month in [3, 4, 5]:
            return 'Spring'
        elif month in [6, 7, 8]:
            return 'Summer'
        else:
            return 'Fall'
    
    df[f'{prefix}_Season'] = df[f'{prefix}_Month'].apply(get_season)
    
    return df

In [14]:
df = extract_date_components(df, 'estimated_time_delivery', 'estimated_delivery')

In [15]:
df

,order_id,user_name,order_status,order_date,order_approved_date,pickup_date,delivered_date,estimated_time_delivery,order_Date,order_Time,...,delivered_Day,delivered_Season,delivered_Hour,delivered_Minute,delivered_AM/PM,delivered_TimeOfDay,estimated_delivery_Year,estimated_delivery_Month,estimated_delivery_Day,estimated_delivery_Season
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,2017-10-02 10:56:00,2017-10-02 11:07:00,2017-10-04 19:55:00,2017-10-10 21:25:00,2017-10-18,2017-10-02,10:56:00,...,10,Fall,21,25,PM,Night,2017,10,18,Fall
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,delivered,2018-07-24 20:41:00,2018-07-26 03:24:00,2018-07-26 14:31:00,2018-08-07 15:27:00,2018-08-13,2018-07-24,20:41:00,...,7,Summer,15,27,PM,Afternoon,2018,8,13,Summer
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,delivered,2018-08-08 08:38:00,2018-08-08 08:55:00,2018-08-08 13:50:00,2018-08-17 18:06:00,2018-09-04,2018-08-08,08:38:00,...,17,Summer,18,6,PM,Evening,2018,9,4,Fall
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,delivered,2017-11-18 19:28:00,2017-11-18 19:45:00,2017-11-22 13:39:00,2017-12-02 00:28:00,2017-12-15,2017-11-18,19:28:00,...,2,Winter,0,28,AM,Night,2017,12,15,Winter
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,delivered,2018-02-13 21:18:00,2018-02-13 22:20:00,2018-02-14 19:46:00,2018-02-16 18:17:00,2018-02-26,2018-02-13,21:18:00,...,16,Winter,18,17,PM,Evening,2018,2,26,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,6359f309b166b0196dbf7ad2ac62bb5a,delivered,2017-03-09 09:54:00,2017-03-09 09:54:00,2017-03-10 11:18:00,2017-03-17 15:08:00,2017-03-28,2017-03-09,09:54:00,...,17,Spring,15,8,PM,Afternoon,2017,3,28,Spring
99437,63943bddc261676b46f01ca7ac2f7bd8,da62f9e57a76d978d02ab5362c509660,delivered,2018-02-06 12:58:00,2018-02-06 13:10:00,2018-02-07 23:22:00,2018-02-28 17:37:00,2018-03-02,2018-02-06,12:58:00,...,28,Winter,17,37,PM,Evening,2018,3,2,Spring
99438,83c1379a015df1e13d02aae0204711ab,737520a9aad80b3fbbdad19b66b37b30,delivered,2017-08-27 14:46:00,2017-08-27 15:04:00,2017-08-28 20:52:00,2017-09-21 11:24:00,2017-09-27,2017-08-27,14:46:00,...,21,Fall,11,24,AM,Morning,2017,9,27,Fall
99439,11c177c8e97725db2631073c19f07b62,5097a5312c8b157bb7be58ae360ef43c,delivered,2018-01-08 21:28:00,2018-01-08 21:36:00,2018-01-12 15:35:00,2018-01-25 23:32:00,2018-02-15,2018-01-08,21:28:00,...,25,Winter,23,32,PM,Night,2018,2,15,Winter
99440,66dea50a8b16d9b4dee7af250b4be1a5,60350aa974b26ff12caad89e55993bd6,delivered,2018-03-08 20:57:00,2018-03-09 11:20:00,2018-03-09 22:11:00,2018-03-16 13:08:00,2018-04-03,2018-03-08,20:57:00,...,16,Spring,13,8,PM,Afternoon,2018,4,3,Spring

In [16]:
df.columns

Index(['order_id', 'user_name', 'order_status', 'order_date',
       'order_approved_date', 'pickup_date', 'delivered_date',
       'estimated_time_delivery', 'order_Date', 'order_Time', 'order_Year',
       'order_Month', 'order_Day', 'order_Season', 'order_Hour',
       'order_Minute', 'order_AM/PM', 'order_TimeOfDay', 'order_approved_Date',
       'order_approved_Time', 'order_approved_Year', 'order_approved_Month',
       'order_approved_Day', 'order_approved_Season', 'order_approved_Hour',
       'order_approved_Minute', 'order_approved_AM/PM',
       'order_approved_TimeOfDay', 'pickup_Date', 'pickup_Time', 'pickup_Year',
       'pickup_Month', 'pickup_Day', 'pickup_Season', 'pickup_Hour',
       'pickup_Minute', 'pickup_AM/PM', 'pickup_TimeOfDay', 'delivered_Date',
       'delivered_Time', 'delivered_Year', 'delivered_Month', 'delivered_Day',
       'delivered_Season', 'delivered_Hour', 'delivered_Minute',
       'delivered_AM/PM', 'delivered_TimeOfDay', 'estimated_delivery_Year',
       'estimated_delivery_Month', 'estimated_delivery_Day',
       'estimated_delivery_Season'],
      dtype='object')

In [117]:
# Remove columns : order_date, order_approved_date,pickup_date, delivered_date 
df = df.drop(['order_date','order_approved_date', 'pickup_date','delivered_date'], axis=1)

In [118]:
df

,order_id,user_name,order_status,estimated_time_delivery,order_Date,order_Time,order_Year,order_Month,order_Day,order_Season,...,delivered_Day,delivered_Season,delivered_Hour,delivered_Minute,delivered_AM/PM,delivered_TimeOfDay,estimated_delivery_Year,estimated_delivery_Month,estimated_delivery_Day,estimated_delivery_Season
0,e481f51cbdc54678b7cc49136f2d6af7,7c396fd4830fd04220f754e42b4e5bff,delivered,2017-10-18,2017-10-02,10:56:00,2017,10,2,Fall,...,10,Fall,21,25,PM,Night,2017,10,18,Fall
1,53cdb2fc8bc7dce0b6741e2150273451,af07308b275d755c9edb36a90c618231,delivered,2018-08-13,2018-07-24,20:41:00,2018,7,24,Summer,...,7,Summer,15,27,PM,Afternoon,2018,8,13,Summer
2,47770eb9100c2d0c44946d9cf07ec65d,3a653a41f6f9fc3d2a113cf8398680e8,delivered,2018-09-04,2018-08-08,08:38:00,2018,8,8,Summer,...,17,Summer,18,6,PM,Evening,2018,9,4,Fall
3,949d5b44dbf5de918fe9c16f97b45f8a,7c142cf63193a1473d2e66489a9ae977,delivered,2017-12-15,2017-11-18,19:28:00,2017,11,18,Fall,...,2,Winter,0,28,AM,Night,2017,12,15,Winter
4,ad21c59c0840e6cb83a9ceb5573f8159,72632f0f9dd73dfee390c9b22eb56dd6,delivered,2018-02-26,2018-02-13,21:18:00,2018,2,13,Winter,...,16,Winter,18,17,PM,Evening,2018,2,26,Winter
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99436,9c5dedf39a927c1b2549525ed64a053c,6359f309b166b0196dbf7ad2ac62bb5a,delivered,2017-03-28,2017-03-09,09:54:00,2017,3,9,Spring,...,17,Spring,15,8,PM,Afternoon,2017,3,28,Spring
99437,63943bddc261676b46f01ca7ac2f7bd8,da62f9e57a76d978d02ab5362c509660,delivered,2018-03-02,2018-02-06,12:58:00,2018,2,6,Winter,...,28,Winter,17,37,PM,Evening,2018,3,2,Spring
99438,83c1379a015df1e13d02aae0204711ab,737520a9aad80b3fbbdad19b66b37b30,delivered,2017-09-27,2017-08-27,14:46:00,2017,8,27,Summer,...,21,Fall,11,24,AM,Morning,2017,9,27,Fall
99439,11c177c8e97725db2631073c19f07b62,5097a5312c8b157bb7be58ae360ef43c,delivered,2018-02-15,2018-01-08,21:28:00,2018,1,8,Winter,...,25,Winter,23,32,PM,Night,2018,2,15,Winter
99440,66dea50a8b16d9b4dee7af250b4be1a5,60350aa974b26ff12caad89e55993bd6,delivered,2018-04-03,2018-03-08,20:57:00,2018,3,8,Spring,...,16,Spring,13,8,PM,Afternoon,2018,4,3,Spring

In [119]:
df.to_csv('C:/Users/Dell/OneDrive/Desktop/Data Engineer Project/Project-1/Original dataset/order.csv', index=False)